CREATE DATABASE IF NOT EXISTS scot;
USE scot;

CREATE USER 'root'@'%' IDENTIFIED BY 'root';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%'  WITH GRANT OPTION;

CREATE USER 'scot'@'%' IDENTIFIED BY 'scot123!@#';
GRANT ALL PRIVILEGES ON *.* TO 'scot'@'%' WITH GRANT OPTION;